# locust.conf
# Locust load testing configuration for SALESTORM Connected API Mode

locustfile = simulation/locust/locustfile.py
host = http://127.0.0.1:8000
users = 1000
spawn-rate = 100
run-time = 30s
headless = true
only-summary = true
